# generated by datamodel-codegen:
#   filename:  nalar-ai.openapi.json

from __future__ import annotations
from enum import StrEnum
from typing import Annotated, Any, Literal
from pydantic import BaseModel, Field, RootModel
from uuid import UUID


class AiPurpose(StrEnum):
    kb_extract = "kb_extract"
    kb_misconceptions = "kb_misconceptions"
    cp_align = "cp_align"
    kb_dedup = "kb_dedup"
    embedding = "embedding"
    turn_analyze = "turn_analyze"
    probe_plan = "probe_plan"
    session_evaluation = "session_evaluation"
    reflection_generation = "reflection_generation"


class AnswerType(StrEnum):
    correct_reasoned = "correct_reasoned"
    correct_unreasoned = "correct_unreasoned"
    misconception = "misconception"
    mixed = "mixed"
    evasive = "evasive"
    manipulation = "manipulation"
    unsure = "unsure"
    safety = "safety"


class BodyChunkSectionV1S1SectionsChunkPost(BaseModel):
    file: Annotated[
        str, Field(json_schema_extra={"contentMediaType": "application/octet-stream"}, title="File")
    ]
    spec: Annotated[
        str, Field(description="JSON: {page_start, page_end, title, next_title}", title="Spec")
    ]


class BodyDetectSectionsV1S1SectionsDetectPost(BaseModel):
    fallback_title: Annotated[
        str | None, Field(max_length=300, min_length=1, title="Fallback Title")
    ] = "Materi"
    file: Annotated[
        str, Field(json_schema_extra={"contentMediaType": "application/octet-stream"}, title="File")
    ]


class CallStatus(StrEnum):
    success = "success"
    error = "error"


class CandidateIn(BaseModel):
    concept_id: Annotated[UUID, Field(title="Concept Id")]
    description: Annotated[str | None, Field(max_length=2000, title="Description")] = ""
    name: Annotated[str, Field(max_length=300, min_length=1, title="Name")]
    similarity: Annotated[float, Field(ge=-1.0, le=1.0, title="Similarity")]


class ChunkKind(StrEnum):
    explanation = "explanation"
    example = "example"
    activity = "activity"
    exercise = "exercise"
    answer_key = "answer_key"
    summary = "summary"
    sidebar = "sidebar"
    other = "other"


class ChunkOut(BaseModel):
    chunk_kind: ChunkKind
    content: Annotated[str, Field(title="Content")]
    content_sha256: Annotated[str, Field(title="Content Sha256")]
    embedding: Annotated[list[float], Field(title="Embedding")]
    heading_path: Annotated[str, Field(title="Heading Path")]
    local_index: Annotated[int, Field(title="Local Index")]
    page_end: Annotated[int, Field(title="Page End")]
    page_start: Annotated[int, Field(title="Page Start")]
    token_count: Annotated[int, Field(title="Token Count")]


class PageEnd(RootModel[int]):
    root: Annotated[int, Field(ge=1, title="Page End")]


class PageStart(RootModel[int]):
    root: Annotated[int, Field(ge=1, title="Page Start")]


class ChunkRefIn(BaseModel):
    content: Annotated[str, Field(max_length=40000, min_length=1, title="Content")]
    heading_path: Annotated[str | None, Field(max_length=2000, title="Heading Path")] = ""
    id: Annotated[UUID, Field(title="Id")]
    kind: ChunkKind
    page_end: Annotated[PageEnd | None, Field(title="Page End")] = None
    page_start: Annotated[PageStart | None, Field(title="Page Start")] = None


class ClassificationSource(StrEnum):
    prefilter = "prefilter"
    model = "model"
    fallback = "fallback"


class ConceptDraftOut(BaseModel):
    description: Annotated[str, Field(title="Description")]
    embedding: Annotated[list[float], Field(title="Embedding")]
    key: Annotated[str, Field(title="Key")]
    name: Annotated[str, Field(title="Name")]
    prerequisite_existing_ids: Annotated[list[UUID], Field(title="Prerequisite Existing Ids")]
    prerequisite_keys: Annotated[list[str], Field(title="Prerequisite Keys")]
    source_chunk_ids: Annotated[list[UUID], Field(title="Source Chunk Ids")]


class ConceptOutcome(StrEnum):
    mastered = "mastered"
    developing = "developing"
    misconception = "misconception"
    not_observed = "not_observed"


class ConceptResultOut(BaseModel):
    concept_id: Annotated[UUID, Field(title="Concept Id")]
    evidence_turn_id: Annotated[UUID | None, Field(title="Evidence Turn Id")]
    initial_misconception_id: Annotated[UUID | None, Field(title="Initial Misconception Id")]
    misconception_id: Annotated[UUID | None, Field(title="Misconception Id")]
    outcome: ConceptOutcome
    resolved_in_session: Annotated[bool, Field(title="Resolved In Session")]


class AnswerTerm(RootModel[str]):
    root: Annotated[str, Field(max_length=100, min_length=1)]


class CoverageOut(BaseModel):
    challenged: Annotated[bool, Field(title="Challenged")]
    concept_id: Annotated[UUID, Field(title="Concept Id")]


class CpBasis(StrEnum):
    judge = "judge"
    no_candidates = "no_candidates"


class Element(RootModel[str]):
    root: Annotated[str, Field(max_length=300, title="Element")]


class CpCandidateIn(BaseModel):
    description: Annotated[str, Field(max_length=4000, min_length=1, title="Description")]
    element: Annotated[Element | None, Field(title="Element")] = None
    outcome_id: Annotated[UUID, Field(title="Outcome Id")]
    similarity: Annotated[float, Field(ge=-1.0, le=1.0, title="Similarity")]


class DedupBasis(StrEnum):
    name_match = "name_match"
    similarity = "similarity"
    judge = "judge"
    no_candidate = "no_candidate"


class Action(StrEnum):
    link = "link"
    create = "create"


class DedupDecisionOut(BaseModel):
    action: Annotated[Action, Field(title="Action")]
    basis: DedupBasis
    existing_concept_id: Annotated[UUID | None, Field(title="Existing Concept Id")]
    key: Annotated[str, Field(title="Key")]
    reason: Annotated[str | None, Field(title="Reason")]
    similarity: Annotated[float | None, Field(title="Similarity")]


class DedupItemIn(BaseModel):
    candidates: Annotated[list[CandidateIn] | None, Field(max_length=10, title="Candidates")] = None
    description: Annotated[str | None, Field(max_length=2000, title="Description")] = ""
    key: Annotated[str, Field(max_length=50, min_length=1, title="Key")]
    name: Annotated[str, Field(max_length=300, min_length=1, title="Name")]


class DedupeIn(BaseModel):
    items: Annotated[list[DedupItemIn], Field(max_length=100, min_length=1, title="Items")]


class DedupeOut(BaseModel):
    decisions: Annotated[list[DedupDecisionOut], Field(title="Decisions")]


class DroppedOut(BaseModel):
    name: Annotated[str, Field(title="Name")]
    reason: Annotated[str, Field(title="Reason")]


class Tag(StrEnum):
    query = "query"
    chunk = "chunk"
    concept = "concept"
    misconception = "misconception"
    cp_statement = "cp_statement"
    library = "library"


class Text(RootModel[str]):
    root: Annotated[str, Field(max_length=30000, min_length=1)]


class EmbedIn(BaseModel):
    tag: Annotated[Tag, Field(title="Tag")]
    texts: Annotated[list[Text], Field(max_length=256, min_length=1, title="Texts")]


class EmbedOut(BaseModel):
    dimensions: Annotated[int, Field(title="Dimensions")]
    embedding_model: Annotated[str, Field(title="Embedding Model")]
    vectors: Annotated[list[list[float]], Field(title="Vectors")]


class EndReason(StrEnum):
    coverage_complete = "coverage_complete"
    turn_limit = "turn_limit"
    time_limit = "time_limit"


class ErrorBody(BaseModel):
    code: Annotated[str, Field(title="Code")]
    details: Annotated[dict[str, Any], Field(title="Details")]
    message: Annotated[str, Field(title="Message")]


class DetectionCue(RootModel[str]):
    root: Annotated[str, Field(max_length=300, min_length=1)]


class EvalMisconceptionIn(BaseModel):
    concept_id: Annotated[UUID, Field(title="Concept Id")]
    detection_cues: Annotated[
        list[DetectionCue] | None, Field(max_length=20, title="Detection Cues")
    ] = None
    id: Annotated[UUID, Field(title="Id")]
    statement: Annotated[str, Field(max_length=1000, min_length=1, title="Statement")]


class EvalTargetIn(BaseModel):
    description: Annotated[str | None, Field(max_length=2000, title="Description")] = ""
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(max_length=300, min_length=1, title="Name")]


class AnswerText(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description="session_turns.answer_text; null or empty when the turn was not answered",
            max_length=20000,
            title="Answer Text",
        ),
    ]


class Kind(StrEnum):
    anchor = "anchor"
    probe = "probe"


class EvaluationPackIn(BaseModel):
    anchor_problem: Annotated[str, Field(max_length=4000, min_length=1, title="Anchor Problem")]
    answer_terms: Annotated[
        list[AnswerTerm], Field(max_length=50, min_length=1, title="Answer Terms")
    ]
    misconceptions: Annotated[
        list[EvalMisconceptionIn] | None, Field(max_length=30, title="Misconceptions")
    ] = None
    pack_version: Annotated[Literal[1], Field(title="Pack Version")]
    reference_reasoning: Annotated[
        str, Field(max_length=8000, min_length=1, title="Reference Reasoning")
    ]
    targets: Annotated[list[EvalTargetIn], Field(max_length=5, min_length=1, title="Targets")]


class ExistingConceptIn(BaseModel):
    description: Annotated[str | None, Field(max_length=2000, title="Description")] = ""
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(max_length=300, min_length=1, title="Name")]


class ExistingLinkOut(BaseModel):
    concept_id: Annotated[UUID, Field(title="Concept Id")]
    source_chunk_ids: Annotated[list[UUID], Field(title="Source Chunk Ids")]


class ExtractConceptsOut(BaseModel):
    concepts: Annotated[list[ConceptDraftOut], Field(title="Concepts")]
    dropped: Annotated[list[DroppedOut], Field(title="Dropped")]
    embedding_model: Annotated[str, Field(title="Embedding Model")]
    existing_links: Annotated[list[ExistingLinkOut], Field(title="Existing Links")]


class FailedConceptOut(BaseModel):
    concept_ref: Annotated[str, Field(title="Concept Ref")]
    error: Annotated[str, Field(title="Error")]


class GuardResult(StrEnum):
    passed = "passed"
    blocked_shape = "blocked_shape"
    blocked_verdict = "blocked_verdict"
    blocked_new_terms = "blocked_new_terms"
    blocked_similarity = "blocked_similarity"
    blocked_drift = "blocked_drift"
    not_run = "not_run"


class HealthOut(BaseModel):
    service: Annotated[str, Field(title="Service")]
    status: Annotated[Literal["ok"], Field(title="Status")]
    version: Annotated[str, Field(title="Version")]


class QuestionBankId(RootModel[str]):
    root: Annotated[str, Field(max_length=100, title="Question Bank Id")]


class LibraryCandidateIn(BaseModel):
    correct_understanding: Annotated[
        str, Field(max_length=2000, min_length=1, title="Correct Understanding")
    ]
    counter_examples: Annotated[
        list[str] | None, Field(max_length=20, title="Counter Examples")
    ] = None
    library_id: Annotated[UUID, Field(title="Library Id")]
    similarity: Annotated[float, Field(ge=-1.0, le=1.0, title="Similarity")]
    statement: Annotated[str, Field(max_length=2000, min_length=1, title="Statement")]
    student_phrasings: Annotated[
        list[str] | None, Field(max_length=20, title="Student Phrasings")
    ] = None


class MisconceptionIn(BaseModel):
    concept_id: Annotated[UUID, Field(title="Concept Id")]
    detection_cues: Annotated[
        list[DetectionCue] | None, Field(max_length=20, title="Detection Cues")
    ] = None
    id: Annotated[UUID, Field(title="Id")]
    statement: Annotated[str, Field(max_length=1000, min_length=1, title="Statement")]


class MisconceptionOut(BaseModel):
    concept_ref: Annotated[str, Field(title="Concept Ref")]
    correct_understanding: Annotated[str, Field(title="Correct Understanding")]
    counter_examples: Annotated[list[str], Field(title="Counter Examples")]
    detection_cues: Annotated[list[str], Field(title="Detection Cues")]
    embedding: Annotated[list[float], Field(title="Embedding")]
    library_id: Annotated[UUID | None, Field(title="Library Id")]
    source_chunk_ids: Annotated[list[UUID], Field(title="Source Chunk Ids")]
    statement: Annotated[str, Field(title="Statement")]


class MoveReasonCode(StrEnum):
    default = "default"
    mixed_answer = "mixed_answer"
    second_wrong_idea = "second_wrong_idea"
    no_change_after_example = "no_change_after_example"
    frustration = "frustration"
    already_covered = "already_covered"
    check_deeper = "check_deeper"


class MoveSource(StrEnum):
    planner = "planner"
    default = "default"
    fixed_rule = "fixed_rule"
    prefilter = "prefilter"
    fallback_invalid = "fallback_invalid"
    fallback_error = "fallback_error"


class PlannerMode(StrEnum):
    table = "table"
    hybrid = "hybrid"


class PrerequisiteEdgeIn(BaseModel):
    concept_id: Annotated[UUID, Field(title="Concept Id")]
    prerequisite_concept_id: Annotated[UUID, Field(title="Prerequisite Concept Id")]


class ProbeStrategy(StrEnum):
    transfer = "transfer"
    request_justification = "request_justification"
    counter_example = "counter_example"
    decompose = "decompose"
    refuse_and_redirect = "refuse_and_redirect"
    deeper_reason = "deeper_reason"
    explain_mechanism = "explain_mechanism"
    simpler_reason = "simpler_reason"


class QuestionSource(StrEnum):
    adapted = "adapted"
    approved = "approved"


class RejectedConceptIn(BaseModel):
    description: Annotated[str | None, Field(max_length=2000, title="Description")] = ""
    name: Annotated[str, Field(max_length=300, min_length=1, title="Name")]


class RetrievalPath(StrEnum):
    link = "link"
    search = "search"
    teacher_confirmed = "teacher_confirmed"


class RetrievalSource(StrEnum):
    material_chunk = "material_chunk"
    cp_outcome = "cp_outcome"
    library = "library"
    concept = "concept"


class RubricDimension(StrEnum):
    claim = "claim"
    evidence = "evidence"
    mechanism = "mechanism"
    transfer = "transfer"


class ClaimItem(RootModel[str]):
    root: Annotated[str, Field(max_length=500, min_length=1)]


class EvidenceItem(RootModel[str]):
    root: Annotated[str, Field(max_length=500, min_length=1)]


class MechanismItem(RootModel[str]):
    root: Annotated[str, Field(max_length=500, min_length=1)]


class TransferItem(RootModel[str]):
    root: Annotated[str, Field(max_length=500, min_length=1)]


class RubricIn(BaseModel):
    claim: Annotated[list[ClaimItem], Field(max_length=5, min_length=5, title="Claim")]
    evidence: Annotated[list[EvidenceItem], Field(max_length=5, min_length=5, title="Evidence")]
    mechanism: Annotated[list[MechanismItem], Field(max_length=5, min_length=5, title="Mechanism")]
    transfer: Annotated[list[TransferItem], Field(max_length=5, min_length=5, title="Transfer")]


class ScoreEvidenceOut(BaseModel):
    quote: Annotated[
        str,
        Field(
            description="The student's own words, verbatim from that turn's answer", title="Quote"
        ),
    ]
    turn_id: Annotated[UUID, Field(title="Turn Id")]


class SectionOut(BaseModel):
    level: Annotated[int, Field(title="Level")]
    ordinal: Annotated[int, Field(title="Ordinal")]
    page_end: Annotated[int, Field(title="Page End")]
    page_start: Annotated[int, Field(title="Page Start")]
    parent_ordinal: Annotated[int | None, Field(title="Parent Ordinal")]
    suggested: Annotated[bool, Field(title="Suggested")]
    title: Annotated[str, Field(title="Title")]


class Source(StrEnum):
    model = "model"
    template = "template"


class SessionReflectionOut(BaseModel):
    content: Annotated[str, Field(description="session_reflections.content", title="Content")]
    source: Annotated[
        Source, Field(description="Not stored; 'template' after two blocked tries", title="Source")
    ]


class Reason(StrEnum):
    scanned = "scanned"
    blank = "blank"


class SkippedPageOut(BaseModel):
    page: Annotated[int, Field(title="Page")]
    reason: Annotated[Reason, Field(title="Reason")]


class TargetConceptIn(BaseModel):
    description: Annotated[str | None, Field(max_length=2000, title="Description")] = ""
    id: Annotated[UUID, Field(title="Id")]
    name: Annotated[str, Field(max_length=300, min_length=1, title="Name")]


class TurnAction(StrEnum):
    probe = "probe"
    end = "end"
    safety_pause = "safety_pause"


class TurnKind(StrEnum):
    anchor = "anchor"
    probe = "probe"


class TurnQualityOut(BaseModel):
    quality: Annotated[
        int,
        Field(description="0 empty or evasive … 4 correct with a clear mechanism", title="Quality"),
    ]
    turn_id: Annotated[UUID, Field(title="Turn Id")]
    turn_index: Annotated[int, Field(title="Turn Index")]


class WarmOut(BaseModel):
    warmed: Annotated[bool, Field(title="Warmed")]


class AlignItemIn(BaseModel):
    candidates: Annotated[list[CpCandidateIn] | None, Field(max_length=10, title="Candidates")] = (
        None
    )
    concept_ref: Annotated[str, Field(max_length=100, min_length=1, title="Concept Ref")]
    description: Annotated[str | None, Field(max_length=2000, title="Description")] = ""
    name: Annotated[str, Field(max_length=300, min_length=1, title="Name")]


class AnalysisOut(BaseModel):
    answer_type: AnswerType
    frustration: Annotated[bool, Field(title="Frustration")]
    key_phrase: Annotated[str | None, Field(title="Key Phrase")]
    misconception_id: Annotated[UUID | None, Field(title="Misconception Id")]
    secondary_misconception_id: Annotated[UUID | None, Field(title="Secondary Misconception Id")]
    source: ClassificationSource


class BankQuestionIn(BaseModel):
    concept_id: Annotated[UUID, Field(title="Concept Id")]
    id: Annotated[
        str,
        Field(description="Stored as question_bank_id", max_length=100, min_length=1, title="Id"),
    ]
    misconception_id: Annotated[UUID | None, Field(title="Misconception Id")] = None
    move: ProbeStrategy
    text: Annotated[str, Field(max_length=500, min_length=1, title="Text")]


class ChunkSectionOut(BaseModel):
    chunks: Annotated[list[ChunkOut], Field(title="Chunks")]
    embedding_model: Annotated[str, Field(title="Embedding Model")]
    skipped_pages: Annotated[list[SkippedPageOut], Field(title="Skipped Pages")]


class ConceptForMisconceptionsIn(BaseModel):
    concept_ref: Annotated[str, Field(max_length=100, min_length=1, title="Concept Ref")]
    description: Annotated[str | None, Field(max_length=2000, title="Description")] = ""
    existing_statements: Annotated[
        list[str] | None, Field(max_length=50, title="Existing Statements")
    ] = None
    library_candidates: Annotated[
        list[LibraryCandidateIn] | None, Field(max_length=10, title="Library Candidates")
    ] = None
    name: Annotated[str, Field(max_length=300, min_length=1, title="Name")]
    source_chunk_ids: Annotated[
        list[UUID], Field(max_length=50, min_length=1, title="Source Chunk Ids")
    ]


class ContextPackIn(BaseModel):
    anchor_problem: Annotated[str, Field(max_length=4000, min_length=1, title="Anchor Problem")]
    answer_terms: Annotated[
        list[AnswerTerm], Field(max_length=50, min_length=1, title="Answer Terms")
    ]
    max_duration_minutes: Annotated[int, Field(ge=1, le=60, title="Max Duration Minutes")]
    max_probes: Annotated[
        int, Field(description="mission_versions.max_turns", ge=1, le=10, title="Max Probes")
    ]
    misconceptions: Annotated[
        list[MisconceptionIn] | None, Field(max_length=30, title="Misconceptions")
    ] = None
    pack_version: Annotated[Literal[1], Field(title="Pack Version")]
    question_bank: Annotated[
        list[BankQuestionIn], Field(max_length=200, min_length=1, title="Question Bank")
    ]
    reference_reasoning: Annotated[
        str,
        Field(
            description="Hidden model answer; never sent to the writer",
            max_length=8000,
            min_length=1,
            title="Reference Reasoning",
        ),
    ]
    targets: Annotated[list[TargetConceptIn], Field(max_length=5, min_length=1, title="Targets")]


class CpAlignmentOut(BaseModel):
    basis: CpBasis
    concept_ref: Annotated[str, Field(title="Concept Ref")]
    outcome_id: Annotated[UUID | None, Field(title="Outcome Id")]
    reason: Annotated[str, Field(title="Reason")]


class DetectSectionsOut(BaseModel):
    has_toc: Annotated[bool, Field(title="Has Toc")]
    page_count: Annotated[int, Field(title="Page Count")]
    pages_without_text: Annotated[list[int], Field(title="Pages Without Text")]
    sections: Annotated[list[SectionOut], Field(title="Sections")]


class EvalTurnIn(BaseModel):
    answer_text: Annotated[
        AnswerText | None,
        Field(
            description="session_turns.answer_text; null or empty when the turn was not answered",
            title="Answer Text",
        ),
    ] = None
    kind: Annotated[Kind, Field(title="Kind")]
    move: Annotated[ProbeStrategy | None, Field(description="prompt_strategy")] = None
    question_text: Annotated[str, Field(max_length=2000, min_length=1, title="Question Text")]
    target_concept_id: Annotated[UUID | None, Field(title="Target Concept Id")] = None
    turn_id: Annotated[
        UUID, Field(description="session_turns.id, returned on every quote", title="Turn Id")
    ]
    turn_index: Annotated[int, Field(ge=0, le=50, title="Turn Index")]


class EvaluateIn(BaseModel):
    context_pack: EvaluationPackIn
    rubric: RubricIn
    turns: Annotated[list[EvalTurnIn], Field(max_length=30, min_length=1, title="Turns")]


class ExtractConceptsIn(BaseModel):
    chunks: Annotated[list[ChunkRefIn], Field(max_length=2000, min_length=1, title="Chunks")]
    existing_concepts: Annotated[
        list[ExistingConceptIn] | None, Field(max_length=1000, title="Existing Concepts")
    ] = None
    existing_prerequisites: Annotated[
        list[PrerequisiteEdgeIn] | None, Field(max_length=5000, title="Existing Prerequisites")
    ] = None
    phase: Annotated[str, Field(max_length=10, min_length=1, title="Phase")]
    rejected_concepts: Annotated[
        list[RejectedConceptIn] | None, Field(max_length=1000, title="Rejected Concepts")
    ] = None
    section_title: Annotated[str, Field(max_length=300, min_length=1, title="Section Title")]
    subject: Annotated[str, Field(max_length=100, min_length=1, title="Subject")]


class GenerateMisconceptionsIn(BaseModel):
    chunks: Annotated[list[ChunkRefIn], Field(max_length=2000, min_length=1, title="Chunks")]
    concepts: Annotated[
        list[ConceptForMisconceptionsIn], Field(max_length=30, min_length=1, title="Concepts")
    ]
    phase: Annotated[str, Field(max_length=10, min_length=1, title="Phase")]
    subject: Annotated[str, Field(max_length=100, min_length=1, title="Subject")]


class GenerateMisconceptionsOut(BaseModel):
    dropped: Annotated[list[DroppedOut], Field(title="Dropped")]
    embedding_model: Annotated[str, Field(title="Embedding Model")]
    failed: Annotated[list[FailedConceptOut], Field(title="Failed")]
    misconceptions: Annotated[list[MisconceptionOut], Field(title="Misconceptions")]


class HistoryTurnIn(BaseModel):
    answer_text: Annotated[str, Field(max_length=20000, title="Answer Text")]
    answer_type: Annotated[
        AnswerType | None, Field(description="The stored analysis; null for the latest answer")
    ] = None
    kind: TurnKind
    misconception_ids: Annotated[
        list[UUID] | None,
        Field(
            description="detected_misconception_id, then secondary_misconception_id",
            max_length=2,
            title="Misconception Ids",
        ),
    ] = None
    move: Annotated[ProbeStrategy | None, Field(description="prompt_strategy")] = None
    question_bank_id: Annotated[QuestionBankId | None, Field(title="Question Bank Id")] = None
    question_text: Annotated[str, Field(max_length=2000, min_length=1, title="Question Text")]
    target_concept_id: Annotated[UUID | None, Field(title="Target Concept Id")] = None
    turn_index: Annotated[int, Field(ge=0, le=50, title="Turn Index")]


class NextTurnIn(BaseModel):
    context_pack: ContextPackIn
    elapsed_seconds: Annotated[int, Field(ge=0, le=86400, title="Elapsed Seconds")]
    history: Annotated[list[HistoryTurnIn], Field(max_length=30, min_length=1, title="History")]
    planner_mode: Annotated[PlannerMode, Field(description="publication_runs.planner_mode")]


class ProbeOut(BaseModel):
    allowed_moves: Annotated[list[ProbeStrategy], Field(title="Allowed Moves")]
    guard_result: GuardResult
    move: ProbeStrategy
    move_source: MoveSource
    question_bank_id: Annotated[str, Field(title="Question Bank Id")]
    question_source: QuestionSource
    question_text: Annotated[str, Field(title="Question Text")]
    reason: Annotated[str, Field(title="Reason")]
    reason_code: MoveReasonCode
    target_concept_id: Annotated[UUID, Field(title="Target Concept Id")]


class RetrievalRefOut(BaseModel):
    id: Annotated[UUID, Field(title="Id")]
    path: RetrievalPath
    rank: Annotated[int, Field(title="Rank")]
    score: Annotated[float | None, Field(title="Score")]
    source: RetrievalSource


class RubricScoreOut(BaseModel):
    dimension: RubricDimension
    evidence: Annotated[
        list[ScoreEvidenceOut],
        Field(description="score_evidence rows; at least one", title="Evidence"),
    ]
    level: Annotated[
        int, Field(description="evaluation_scores.ai_level and final_level", title="Level")
    ]
    rationale: Annotated[str, Field(title="Rationale")]


class WarmIn(BaseModel):
    context_pack: ContextPackIn


class AlignCpIn(BaseModel):
    items: Annotated[list[AlignItemIn], Field(max_length=100, min_length=1, title="Items")]


class AlignCpOut(BaseModel):
    alignments: Annotated[list[CpAlignmentOut], Field(title="Alignments")]


class EvaluateOut(BaseModel):
    concept_results: Annotated[list[ConceptResultOut], Field(title="Concept Results")]
    reflection: SessionReflectionOut
    scores: Annotated[list[RubricScoreOut], Field(title="Scores")]
    summary: Annotated[str, Field(description="session_evaluations.summary", title="Summary")]
    turn_quality: Annotated[
        list[TurnQualityOut],
        Field(description="session_evaluations.turn_quality", title="Turn Quality"),
    ]


class InvocationOut(BaseModel):
    cache_read_tokens: Annotated[int, Field(title="Cache Read Tokens")]
    cache_write_tokens: Annotated[int, Field(title="Cache Write Tokens")]
    cost_usd: Annotated[float, Field(title="Cost Usd")]
    error_message: Annotated[str | None, Field(title="Error Message")]
    input_tokens: Annotated[int, Field(title="Input Tokens")]
    latency_ms: Annotated[int, Field(title="Latency Ms")]
    model: Annotated[str, Field(title="Model")]
    output_tokens: Annotated[int, Field(title="Output Tokens")]
    prompt_version: Annotated[str, Field(title="Prompt Version")]
    provider: Annotated[str, Field(title="Provider")]
    purpose: AiPurpose
    request_id: Annotated[str, Field(title="Request Id")]
    retrieval: Annotated[list[RetrievalRefOut], Field(title="Retrieval")]
    status: CallStatus


class NextTurnOut(BaseModel):
    action: TurnAction
    analysis: AnalysisOut
    coverage: Annotated[list[CoverageOut], Field(title="Coverage")]
    end_reason: EndReason | None
    probe: ProbeOut | None
    safety_message: Annotated[str | None, Field(title="Safety Message")]


class EnvelopeAlignCpOut(BaseModel):
    invocations: Annotated[list[InvocationOut], Field(title="Invocations")]
    result: AlignCpOut
    warnings: Annotated[list[str], Field(title="Warnings")]


class EnvelopeChunkSectionOut(BaseModel):
    invocations: Annotated[list[InvocationOut], Field(title="Invocations")]
    result: ChunkSectionOut
    warnings: Annotated[list[str], Field(title="Warnings")]


class EnvelopeDedupeOut(BaseModel):
    invocations: Annotated[list[InvocationOut], Field(title="Invocations")]
    result: DedupeOut
    warnings: Annotated[list[str], Field(title="Warnings")]


class EnvelopeDetectSectionsOut(BaseModel):
    invocations: Annotated[list[InvocationOut], Field(title="Invocations")]
    result: DetectSectionsOut
    warnings: Annotated[list[str], Field(title="Warnings")]


class EnvelopeEmbedOut(BaseModel):
    invocations: Annotated[list[InvocationOut], Field(title="Invocations")]
    result: EmbedOut
    warnings: Annotated[list[str], Field(title="Warnings")]


class EnvelopeEvaluateOut(BaseModel):
    invocations: Annotated[list[InvocationOut], Field(title="Invocations")]
    result: EvaluateOut
    warnings: Annotated[list[str], Field(title="Warnings")]


class EnvelopeExtractConceptsOut(BaseModel):
    invocations: Annotated[list[InvocationOut], Field(title="Invocations")]
    result: ExtractConceptsOut
    warnings: Annotated[list[str], Field(title="Warnings")]


class EnvelopeGenerateMisconceptionsOut(BaseModel):
    invocations: Annotated[list[InvocationOut], Field(title="Invocations")]
    result: GenerateMisconceptionsOut
    warnings: Annotated[list[str], Field(title="Warnings")]


class EnvelopeNextTurnOut(BaseModel):
    invocations: Annotated[list[InvocationOut], Field(title="Invocations")]
    result: NextTurnOut
    warnings: Annotated[list[str], Field(title="Warnings")]


class EnvelopeWarmOut(BaseModel):
    invocations: Annotated[list[InvocationOut], Field(title="Invocations")]
    result: WarmOut
    warnings: Annotated[list[str], Field(title="Warnings")]


class ErrorEnvelope(BaseModel):
    error: ErrorBody
    invocations: Annotated[list[InvocationOut], Field(title="Invocations")]
    request_id: Annotated[str | None, Field(title="Request Id")]
