from typing import Protocol
from uuid import UUID


class Authz(Protocol):
    """Scope checks for the caller. Every check requires an active membership."""

    async def is_platform_admin(self, user_id: UUID) -> bool: ...

    async def manages_kb(self, user_id: UUID, kb_id: UUID) -> bool: ...

    async def teaches_class(self, user_id: UUID, class_id: UUID) -> bool: ...

    async def teaches_class_subject(
        self, user_id: UUID, class_id: UUID, school_subject_id: UUID
    ) -> bool: ...

    async def teaches_subject(
        self, user_id: UUID, school_id: UUID, school_subject_id: UUID
    ) -> bool: ...

    async def teaches_publication(self, user_id: UUID, publication_id: UUID) -> bool: ...

    async def teaches_run(self, user_id: UUID, run_id: UUID) -> bool: ...

    async def teaches_session(self, user_id: UUID, session_id: UUID) -> bool: ...

    async def can_read_kb(self, user_id: UUID, kb_id: UUID) -> bool: ...

    async def owns_kb(self, user_id: UUID, kb_id: UUID) -> bool: ...

    async def is_mission_creator(self, user_id: UUID, mission_id: UUID) -> bool: ...

    async def is_enrolled(self, user_id: UUID, class_id: UUID) -> bool: ...

    async def owns_session(self, user_id: UUID, session_id: UUID) -> bool: ...

    async def is_linked_parent(self, user_id: UUID, student_id: UUID) -> bool: ...

    async def is_school_admin(self, user_id: UUID, school_id: UUID) -> bool: ...

    async def can_manage_roster(self, user_id: UUID, import_id: UUID) -> bool: ...

    async def is_school_teacher(self, user_id: UUID, school_id: UUID) -> bool: ...

    async def is_school_student(self, user_id: UUID, school_id: UUID) -> bool: ...

    async def teaches_student(self, user_id: UUID, student_id: UUID) -> bool: ...
